apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-role
rules:
- apiGroups: ["*"]
  resources:
    - "*"
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-crb
  annotations:
    helm.sh/hook: "pre-upgrade, pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook-weight: "0"
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io
