apiVersion: v1
kind: Service
metadata:
  name: ostrich-sdk
spec:
  selector:
    app: ostrich-sdk
  type: NodePort
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: {{ (index .Values "ostrich-sdk").nodePort }}
