# This file contains the default keys for the template.
# If one of the keys is not present in the user's ostrich.yaml, 
# it will be taken from this file.
template:
  params:
    input:
      src: "src"
      bin: "bin"
default:
  valueNoExist: default
  valueExist: default
