#! /usr/bin/env python 

import os
import sys
import tempfile
import logging
import yaml
from src.exceptions import OstrichError
from src.toolkit import ExecutionParams, InternalPaths
from src.constants import apply_logging_defaults
from src.engine import entry_point, configure_cli
from src.generator import manage_templates
from src.discovery import manage_sources

def display_help(halt=True):
    print("""Usage: ost <command> [options]

Core Commands:
  - run      : Execute a task defined in your manifest
  - template : Manage Ostrich templates
  - registry : OCI repository operations
  - config   : View/Edit system settings
  - help     : Show this documentation

Options:
  -d, --debug      : Enable verbose logging
  -f, --file <val> : Specify manifest (default: ostrich.yaml)
  -o, --output <dir>: Set scratch directory
  -dr, --dry-run   : Generate but do not execute
  --rm             : Purge scratch directory before start
  --nodeps         : Ignore task dependencies
""")
    if halt: sys.exit(1)

def main():
    params = ExecutionParams()
    args = sys.argv[1:]
    
    if not args:
        display_help()

    # Early log check
    if '-d' in args or '--debug' in args:
        logging.getLogger().setLevel(logging.DEBUG)

    apply_logging_defaults()

    # Pass everything to ExecutionParams for parsing
    params.extra_args = args
    params.parse_cli_flags()

    if params.show_help:
        display_help(False)
        return

    if not params.extra_args:
        display_help()

    op = params.extra_args[0]
    params.active_operation = op
    params.extra_args = params.extra_args[1:] # consume operation

    try:
        if op == "help":
            display_help(False)
        elif op == "template":
            manage_templates(params)
        elif op == "config":
            configure_cli(params)
        elif op == "registry":
            manage_sources(params)
        elif op == "run":
            if not params.extra_args:
                raise OstrichError("Command 'run' requires a task name.")
            params.active_operation = params.extra_args[0]
            params.extra_args = params.extra_args[1:]
            
            params.initialize_manifest()
            
            # Workspace setup
            if params.scratch_dir is None:
                params.scratch_dir = tempfile.mkdtemp(prefix="ost-")
            
            entry_point(params)
        else:
            # Legacy or direct run?
            logging.error("Unknown command: %s", op)
            display_help()

    except OstrichError as err:
        logging.fatal("Ostrich Error: %s", err)
        if logging.getLogger().isEnabledFor(logging.DEBUG):
            logging.exception(err)
        sys.exit(err.status)
    except Exception as exc:
        logging.fatal("Unexpected Error: %s", exc)
        if logging.getLogger().isEnabledFor(logging.DEBUG):
            logging.exception(exc)
        sys.exit(1)

if __name__ == "__main__":
    # ASCII art...
    if "--nologo" not in sys.argv:
        print(r'''                              _              
     ____   ___  _____  ___  |_| ___  __   _  
    / __ \ / __||_   _||   ) | |/ __||  |_| | 
    |(oO)| \__ \  | |  |   \ | |\__ \)   _  | 
    \_\/_/ |___/  |_|  |_|\_\|_||___/|__| |_|_  _
      ||                            ___   __| || | __
      ||                           / __| / _` || |/ /
                                   \__ \| (_| ||   < 
                                   |___/ \__,_||_|\_\
''', flush=True)
    main()
